/* Create by Stallone L. S. (@st-all-one) - 2026 - License: MPL-2.0
 *
 * Copyright (c) 2026, Stallone L. S. (@st-all-one)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

import type { CalculationNode, RationalValue, SerializedCalculation } from "./ast/types.ts";
import type { RationalNumber } from "./core/rational.ts";
import { DEFAULT_DECIMAL_PRECISION, ROUNDING_IDS, type RoundingStrategy } from "./core/constants.ts";
import { applyRounding } from "./core/rounding.ts";
import { getLocale } from "./output_internal/i18n.ts";
import type { CalcAUYCustomOutput, CalcAUYCustomOutputContext, CalcAUYLocaleA11y } from "./output_internal/types.ts";
import { toSubscript } from "./output_internal/unicode.ts";
import { renderAST } from "./output_internal/renderer.ts";
import { performSlice, performSliceByRatio } from "./output_internal/slicer.ts";
import { renderMermaidSequence } from "./output_internal/mermaid_sequence_renderer.ts";
import type { OutputOptions } from "./output_internal/types.ts";
import { getSubLogger, startSpan } from "./utils/logger.ts";
import type { InstanceConfig } from "./core/types.ts";

const logger = getSubLogger("output");

/**
 * Supported output keys for the toJSON method.
 */
export type OutputKey =
    | "toStringNumber"
    | "toFloatNumber"
    | "toScaledBigInt"
    | "toRawInternalNumber"
    | "toMonetary"
    | "toLaTeX"
    | "toUnicode"
    | "toMermaidGraph"
    | "toVerbalA11y"
    | "toSlice"
    | "toSliceByRatio"
    | "toAuditTrace";

/**
 * CalcAUYOutput - Immutable container for calculation results and multi-format exports.
 *
 * This class is generated by the `CalcAUYLogic.commit()` method. It encapsulates the final
 * result (as a `RationalNumber`) and the original AST, allowing developers to extract
 * information in the most suitable format for various channels (UI, Reports, Logs, A11y).
 *
 * @class
 */
export class CalcAUYOutput {
    readonly #result: RationalNumber;
    readonly #ast: CalculationNode;
    readonly #roundStrategy: RoundingStrategy;
    readonly #signature: string;
    readonly #config: Required<InstanceConfig>;
    readonly #cache: Map<number, RationalNumber> = new Map<number, RationalNumber>();
    readonly #outputCache: Map<string, string | Uint8Array> = new Map();
    #cachedLiveTrace: SerializedCalculation | null = null;
    #cachedMethods: CalcAUYCustomOutputContext["methods"] | null = null;
    #cachedResultJSON: RationalValue | null = null;

    static readonly #formatterCache = new Map<string, Intl.NumberFormat>();

    public constructor(
        result: RationalNumber,
        ast: CalculationNode,
        roundStrategy: RoundingStrategy,
        signature: string,
        config: Required<InstanceConfig>,
    ) {
        this.#result = result;
        this.#ast = ast;
        this.#roundStrategy = roundStrategy;
        this.#signature = signature;
        this.#config = config;
    }

    private getRounded(precision: number): RationalNumber {
        if (!this.#cache.has(precision)) {
            const rounded: RationalNumber = applyRounding(this.#result, this.#roundStrategy, precision);
            this.#cache.set(precision, rounded);
        }
        // deno-lint-ignore no-non-null-assertion
        return this.#cache.get(precision)!;
    }

    private getEffectivePrecision(options?: OutputOptions): number {
        if (options?.decimalPrecision !== undefined) { return options.decimalPrecision; }
        return this.#roundStrategy === "NONE" ? 50 : DEFAULT_DECIMAL_PRECISION;
    }

    private getResultJSON(): RationalValue {
        if (!this.#cachedResultJSON) {
            this.#cachedResultJSON = this.#result.toJSON() as RationalValue;
        }
        return this.#cachedResultJSON;
    }

    /**
     * Returns the result as a decimal string with specified precision.
     *
     * @param options - Output options (decimalPrecision).
     * @returns The formatted decimal string.
     *
     * @example Financial: Summary of a Tax Assessment
     * ```ts
     * const Audit = CalcAUY.create({ contextLabel: "tax-audit", salt: "k-99" });
     *
     * const output = await Audit.from(10000)
     *   .add("2.5%") // Service fee
     *   .setMetadata("reason", "Standard municipal levy")
     *   .commit();
     *
     * console.log(output.toStringNumber()); // "10250.00"
     * ```
     */
    public toStringNumber(options?: OutputOptions): string {
        using _span = startSpan("toStringNumber", logger, options);
        return this.toStringNumberInternal(options);
    }

    private toStringNumberInternal(options?: OutputOptions): string {
        const p: number = this.getEffectivePrecision(options);
        const isNone = this.#roundStrategy === "NONE";
        const cacheKey = `toStringNumber:${p}:${isNone}`;
        if (this.#outputCache.has(cacheKey)) { return this.#outputCache.get(cacheKey) as string; }

        const result = isNone ? this.#result.toDecimalString(p) : this.getRounded(p).toDecimalString(p);

        // If NONE, remove unnecessary trailing zeros to show a "clean" value
        const finalResult = isNone ? result.replace(/\.?0+$/, "").replace(/\.$/, "") || "0" : result;

        this.#outputCache.set(cacheKey, finalResult);
        return finalResult;
    }

    /**
     * Returns the result as a primitive float number.
     *
     * **NOTE**: This method is **NOT RECOMMENDED** for mid-process usage.
     * Float numbers are subject to `IEEE 754 imprecision`.
     *
     * @param options - Output options.
     * @returns The result as a number (IEEE 754).
     *
     * @example Healthcare: Threshold Monitoring for Dosage Safety
     * ```ts
     * const Pharmacy = CalcAUY.create({ contextLabel: "drug-safety", salt: "vault-01" });
     *
     * const dose = await Pharmacy.from(12.5) // Patient weight
     *   .mult(0.15) // Dosage factor
     *   .commit();
     *
     * // Using float for quick comparison or external charting libraries
     * if (dose.toFloatNumber() > 1.5) alert("Critical Level Detected");
     * ```
     */
    public toFloatNumber(options?: OutputOptions): number {
        using _span = startSpan("toFloatNumber", logger, options);
        return Number.parseFloat(this.toStringNumberInternal(options));
    }

    /**
     * Returns the result as a BigInt scaled by the specified precision.
     *
     * @param options - Output options.
     * @returns The scaled BigInt (e.g., 10.50 with precision 2 returns 1050n).
     *
     * @example Legal: Storing Penalty Units in an External Database
     * ```ts
     * const Court = CalcAUY.create({ contextLabel: "sentencing", salt: "justice-key" });
     *
     * const penalty = await Court.from(30).mult(1.5).commit();
     *
     * // Store "45.00" as 4500 in a database column for fixed-point safety
     * const dbValue = penalty.toScaledBigInt({ decimalPrecision: 2 }); // 4500n
     * ```
     */
    public toScaledBigInt(options?: OutputOptions): bigint {
        using _span = startSpan("toScaledBigInt", logger, options);
        return this.toScaledBigIntInternal(options);
    }

    private toScaledBigIntInternal(options?: OutputOptions): bigint {
        const p: number = this.getEffectivePrecision(options);
        const pScale: bigint = 10n ** BigInt(p);
        const rounded: RationalNumber = this.getRounded(p);
        return (rounded.n * pScale) / rounded.d;
    }

    /**
     * Returns the raw internal numerator and denominator.
     *
     * @returns An object with { n: bigint, d: bigint }.
     *
     * @example Legal: Exporting Exact Fractions for Court Records
     * ```ts
     * const Judiciary = CalcAUY.create({ contextLabel: "litigation", salt: "justice-key" });
     *
     * const settlement = await Judiciary.from(15000).mult("5%").commit();
     *
     * const { n, d } = settlement.toRawInternalNumber();
     * console.log(`Rational Evidence: ${n}/${d}`);
     * ```
     */
    public toRawInternalNumber(): { n: bigint; d: bigint } {
        using _span = startSpan("toRawInternalNumber", logger, {});
        return this.toRawInternalNumberInternal();
    }

    private toRawInternalNumberInternal(): { n: bigint; d: bigint } {
        return { n: this.#result.n, d: this.#result.d };
    }

    /**
     * Returns the complete execution trace as a live object for programmatic inspection.
     *
     * @returns The serialized calculation object.
     *
     * @example Healthcare: Real-Time Patient Safety Monitoring
     * ```ts
     * const Safety = CalcAUY.create({ contextLabel: "safety-monitor", salt: "icu-key" });
     *
     * const output = await Safety.from(100).add(50).commit();
     * const trace = output.toLiveTrace();
     *
     * console.log(`Audit jurisdiction: ${trace.contextLabel}`);
     * console.log(`Signature: ${trace.signature}`);
     * ```
     */
    public toLiveTrace(): SerializedCalculation {
        using _span = startSpan("toLiveTrace", logger, {});
        return this.toLiveTraceInternal();
    }
    private toLiveTraceInternal(): SerializedCalculation {
        if (!this.#cachedLiveTrace) {
            this.#cachedLiveTrace = {
                // Optimization: Shallow copy of the root. AST nodes are immutable by design.
                ast: { ...this.#ast },
                finalResult: this.getResultJSON(),
                roundStrategy: this.#roundStrategy,
                signature: this.#signature,
                contextLabel: this.#config.contextLabel,
            };
        }
        return { ...this.#cachedLiveTrace };
    }

    /**
     * Formats the result as a currency string based on the locale.
     *
     * @param options - Output options (locale, currency).
     * @returns The localized currency string.
     *
     * @example Financial: Formatting Branch Balance
     * ```ts
     * const Branch = CalcAUY.create({ contextLabel: "branch-banking", salt: "vault-salt" });
     *
     * const balance = await Branch.from(1_250_000).sub(25_000).commit();
     *
     * // Locale Variation (Default/pt-BR)
     * console.log(balance.toMonetary()); // "R$ 1.225.000,00"
     *
     * // Locale Variation: en-US (BRL)
     * console.log(balance.toMonetary({ locale: "en-US" })); // "$1,225,000.00"
     *
     * // Locale Variation: fr-FR (EUR)
     * console.log(balance.toMonetary({ locale: "fr-FR" })); // "1 225 000,00 €"
     * ```
     */
    public toMonetary(options?: OutputOptions): string {
        using _span = startSpan("toMonetary", logger, options);
        return this.toMonetaryInternal(options);
    }

    private toMonetaryInternal(options?: OutputOptions): string {
        const p: number = this.getEffectivePrecision(options);
        const loc = getLocale(options?.locale);
        const currency: string = options?.currency ?? loc.currency;
        const val: string = this.toStringNumberInternal(options);

        const numberValue = Number.parseFloat(val);
        if (Number.isNaN(numberValue)) { return val; }

        const cacheKey = `${loc.locale}:${currency}:${p}:${this.#roundStrategy === "NONE"}`;
        let formatter = CalcAUYOutput.#formatterCache.get(cacheKey);
        if (!formatter) {
            formatter = new Intl.NumberFormat(loc.locale, {
                style: "currency",
                currency,
                minimumFractionDigits: p,
                maximumFractionDigits: p,
            });
            CalcAUYOutput.#formatterCache.set(cacheKey, formatter);
        }

        return formatter.format(numberValue);
    }

    /**
     * Returns the calculation represented in LaTeX format.
     *
     * @param options - Output options.
     * @returns The LaTeX string.
     *
     * @example Scientific: Documenting Dosage Formulas in Academic Research
     * ```ts
     * const Lab = CalcAUY.create({ contextLabel: "pharmaceutics", salt: "lab-key" });
     *
     * const protocol = await Lab.from(500).mult(Lab.from(1.73).div(1.85)).commit();
     *
     * const latex = protocol.toLaTeX();
     * console.log(latex); // \text{round}_{\text{NBR-5891}}(500 \times \left( \frac{1.73}{1.85} \right), 2) = 467.57
     * ```
     */
    public toLaTeX(options?: OutputOptions): string {
        using _span = startSpan("toLaTeX", logger, options);
        return this.toLaTeXInternal(options);
    }

    private toLaTeXInternal(options?: OutputOptions): string {
        const p: number = this.getEffectivePrecision(options);
        const isNone = this.#roundStrategy === "NONE";
        const cacheKey = `toLaTeX:${p}:${isNone}`;
        if (this.#outputCache.has(cacheKey)) { return this.#outputCache.get(cacheKey) as string; }

        const base: string = renderAST(this.#ast, "latex");
        let roundedStr: string = this.toStringNumberInternal(options);
        // Escape % in LaTeX result to prevent comment errors
        roundedStr = roundedStr.replace(/%/g, String.raw`\%`);
        const strategyName: string = ROUNDING_IDS[this.#roundStrategy];
        const result = String.raw`\text{round}_{\text{${strategyName}}}(${base}, ${p}) = ${roundedStr}`;
        this.#outputCache.set(cacheKey, result);
        return result;
    }

    /**
     * Returns the calculation represented in Unicode (CLI-friendly) format.
     *
     * @param options - Output options.
     * @returns The Unicode string.
     *
     * @example Legal: Quick Review of Penalty Aggregation
     * ```ts
     * const Court = CalcAUY.create({ contextLabel: "court-audit", salt: "justice-key" });
     *
     * const fine = await Court.from(5000).mult(1.5).add(1200).commit();
     *
     * console.log(fine.toUnicode()); // roundₙᵦᵣ₋₅₈₉₁(5000 × 1.5 + 1200, 2) = 8700.00
     * ```
     */
    public toUnicode(options?: OutputOptions): string {
        using _span = startSpan("toUnicode", logger, options);
        return this.toUnicodeInternal(options);
    }

    private toUnicodeInternal(options?: OutputOptions): string {
        const p: number = this.getEffectivePrecision(options);
        const isNone = this.#roundStrategy === "NONE";
        const cacheKey = `toUnicode:${p}:${isNone}`;
        if (this.#outputCache.has(cacheKey)) { return this.#outputCache.get(cacheKey) as string; }

        const base: string = renderAST(this.#ast, "unicode");
        const strategyName: string = ROUNDING_IDS[this.#roundStrategy];
        const subStrategy: string = toSubscript(strategyName);
        const result = `round${subStrategy}(${base}, ${p}) = ${this.toStringNumberInternal(options)}`;
        this.#outputCache.set(cacheKey, result);
        return result;
    }

    /**
     * Returns a Mermaid.js sequence diagram representing the calculation flow.
     *
     * @param options - Output options (locale).
     * @returns The Mermaid diagram string.
     *
     * @example Financial: Visualizing Tax Calculation Steps
     * ```ts
     * const Taxes = CalcAUY.create({ contextLabel: "taxation", salt: "audit-salt", sensitive: false });
     *
     * const calc = await Taxes.from(100).add("15%").commit();
     *
     * console.log(calc.toMermaidGraph());
     * //sequenceDiagram
     * //   autonumber
     * //   participant Ctx_taxation as Context: taxation
     * //
     * //   activate Ctx_taxation
     * //   Note over Ctx_taxation: Ingestion of Operands:<br/>• 100<br/>• 15%
     * //   Ctx_taxation->>Ctx_taxation: Operation: add
     * //   Note over Ctx_taxation: 26-05-03 13:23 (UTC)<br/>Final Closing and Signature<br/>Signature: (Sig: a633a602...)
     * //   deactivate Ctx_taxation
     * ```
     */
    public toMermaidGraph(options?: OutputOptions): string {
        using _span = startSpan("toMermaidGraph", logger, options);
        return this.toMermaidGraphInternal(options);
    }

    private toMermaidGraphInternal(options?: OutputOptions): string {
        const loc = getLocale(options?.locale);
        const cacheKey = `toMermaidGraph:${loc.locale}`;
        let graph = this.#outputCache.get(cacheKey) as string;
        if (graph === undefined) {
            graph = renderMermaidSequence(this.#ast, this.#config, this.#signature, loc);
            this.#outputCache.set(cacheKey, graph);
        }
        return graph;
    }

    /**
     * Generates a natural language (verbal) translation of the calculation for accessibility.
     *
     * @param options - Output options (locale, decimalPrecision).
     * @param customLocale - Optional custom locale override.
     * @returns The verbal description of the calculation.
     *
     * @example Healthcare: Audible Confirmation of Drug Dosage for Nurses
     * ```ts
     * const Hospital = CalcAUY.create({
     *      contextLabel: "icu-dosage",
     *      salt: "lab-key",
     *      roundStrategy: "HALF_UP"
     * });
     *
     * const dose = await Hospital.from(12.5).mult(0.15).commit();
     *
     * // Primary Example (English/en-US)
     * console.log(dose.toVerbalA11y({ locale: "en-US" }));
     * // "12.5 multiplied by 0.15 is equal to 1 point 88 (Rounding: HALF-UP for 2 decimal places)."
     *
     * // Locale Variation: Brazil (pt-BR)
     * console.log(dose.toVerbalA11y({ locale: "pt-BR" }));
     * // "12.5 multiplicado por 0.15 é igual a 1 vírgula 88 (Arredondamento: HALF-UP para 2 casas decimais)."
     *
     * // Locale Variation: Spain (es-ES)
     * console.log(dose.toVerbalA11y({ locale: "es-ES" }));
     * // "12.5 multiplicado por 0.15 es igual a 1 coma 88 (Redondeo: HALF-UP para 2 decimales)."
     *
     * // Locale Variation: Spain (fr-FR)
     * console.log(dose.toVerbalA11y({ locale: "fr-FR" }));
     * // "12.5 multiplié par 0.15 est égal à 1 virgule 88 (Arrondi: HALF-UP pour 2 décimales)."
     *
     * // Locale Variation: Spain (ja-JP)
     * console.log(dose.toVerbalA11y({ locale: "ja-JP" }));
     * // "12.5 かける 0.15 は 1 点 88 (丸め: HALF-UP で 2 桁)."
     * ```
     */
    public toVerbalA11y(options?: OutputOptions, customLocale?: CalcAUYLocaleA11y): string {
        using _span = startSpan("toVerbalA11y", logger, options);
        return this.toVerbalA11yInternal(options, customLocale);
    }

    private toVerbalA11yInternal(options?: OutputOptions, customLocale?: CalcAUYLocaleA11y): string {
        const p: number = this.getEffectivePrecision(options);
        const loc = customLocale || getLocale(options?.locale);
        const base: string = renderAST(this.#ast, "verbal", loc);
        const strategyName: string = ROUNDING_IDS[this.#roundStrategy];
        const finalValueStr: string = this.toStringNumberInternal(options).replace(".", loc.voicedSeparator);
        const { phrases } = loc;
        return `${base}${phrases.isEqual}${finalValueStr} (${phrases.rounding}: ${strategyName} ${phrases.for} ${p} ${phrases.decimalPlaces}).`;
    }

    /**
     * Slices the result into equal parts, distributing remainder cents via Largest Remainder Method.
     *
     * @param parts - Number of parts to divide the total.
     * @param options - Output options.
     * @returns Array of decimal strings representing the parts.
     *
     * @example Legal: Dividing an Estate Among Equal Heirs
     * ```ts
     * const Probate = CalcAUY.create({ contextLabel: "estate-division", salt: "justice-key" });
     *
     * const total = await Probate.from(10.00).commit();
     *
     * // Division of 10.00 into 3 parts:
     * const shares = total.toSlice(3);
     * console.log(shares); // ["3.34", "3.33", "3.33"] -> exactly 10.00
     * ```
     */
    public toSlice(parts: number, options?: OutputOptions): string[] {
        using _span = startSpan("toSlice", logger, { ...options, parts });
        return this.toSliceInternal(parts, options);
    }

    private toSliceInternal(parts: number, options?: OutputOptions): string[] {
        const p: number = this.getEffectivePrecision(options);
        const totalCents: bigint = this.toScaledBigIntInternal(options);
        return performSlice(totalCents, parts, p);
    }

    /**
     * Slices the result based on specified ratios, distributing remainder cents proportionally.
     *
     * @param ratios - Array of ratios (percentages as strings or numbers).
     * @param options - Output options.
     * @returns Array of decimal strings representing the proportional parts.
     *
     * @example Financial: Distributing Profits based on Share Ratios
     * ```ts
     * const Equity = CalcAUY.create({ contextLabel: "equity-split", salt: "hq-salt" });
     *
     * const profits = await Equity.from(1000).commit();
     *
     * // Distribute profits:
     * const split = profits.toSliceByRatio(["5%", "70%", "3.64%", "21,36%"]);
     * console.log(split); // [ "50.19", "702.53", "36.53", "210.75" ] -> exactly 1000.00
     * ```
     */
    public toSliceByRatio(ratios: (number | string)[], options?: OutputOptions): string[] {
        using _span = startSpan("toSliceByRatio", logger, { ...options, ratios });
        return this.toSliceByRatioInternal(ratios, options);
    }

    private toSliceByRatioInternal(ratios: (number | string)[], options?: OutputOptions): string[] {
        const p: number = this.getEffectivePrecision(options);
        const totalCents: bigint = this.toScaledBigIntInternal(options);
        return performSliceByRatio(totalCents, ratios, p);
    }

    /**
     * Returns the finalized audit trace as a signed JSON string.
     *
     * @returns The signed JSON audit trace.
     *
     * @example Legal: Storing Signed Forensic Evidence for Court
     * ```ts
     * const Judiciary = CalcAUY.create({ contextLabel: "litigation", salt: "justice-key" });
     *
     * const verdict = await Judiciary.from(50000).mult(1.2).setMetadata("reason", "arrears").commit();
     *
     * // Save this JSON to a database as an immutable proof of calculation
     * console.log(verdict.toAuditTrace());
     * // {"ast":{"kind":"operation","type":"mul","operands":[{"kind":"literal","value":{"n":"50000","d":"1"},"originalInput":"50000"},{"kind":"literal","value":{"n":"6","d":"5"},"originalInput":"1.2"}],"metadata":{"reason":"arrears","timestamp":"2026-05-03T13:39:49.029Z"}},"finalResult":{"n":"60000","d":"1"},"roundStrategy":"NBR5891","signature":"f796f67a8454eac8b1cabcd411ec64328dabf8cb1ef59422321ce5acfb9f526b","contextLabel":"litigation"}
     * ```
     */
    public toAuditTrace(): string {
        using _span = startSpan("toAuditTrace", logger, {});
        return this.toAuditTraceInternal();
    }

    private toAuditTraceInternal(): string {
        const cacheKey = "auditTrace";
        let trace = this.#outputCache.get(cacheKey) as string;
        if (trace === undefined) {
            trace = JSON.stringify(this.toLiveTraceInternal());
            this.#outputCache.set(cacheKey, trace);
        }
        return trace;
    }

    /**
     * Returns a JSON representation of multiple output formats.
     *
     * @param outputs - Array of output keys to include.
     * @param options - Output options.
     * @returns A JSON string containing requested formats.
     *
     * @example Financial: Integrating Calculation Results with a Web Dashboard
     * ```ts
     * const Finance = CalcAUY.create({ contextLabel: "fin-ops", salt: "hq-salt" });
     *
     * const projection = await Finance.from(1000).mult("1.08").commit();
     *
     * // Export specific formats for API consumption
     * const apiResponse = projection.toJSON(["toMonetary", "toVerbalA11y", "toAuditTrace"]);
     * ```
     */
    public toJSON<T extends OutputKey>(
        outputs?: T[],
        options?: OutputOptions,
    ): string {
        using _span = startSpan("toJSON", logger, { outputs, options });
        const keys: OutputKey[] = (outputs as OutputKey[])
            ?? [
                "toStringNumber",
                "toScaledBigInt",
                "toMonetary",
                "toLaTeX",
                "toUnicode",
                "toVerbalA11y",
                "toAuditTrace",
            ];
        const res: Record<string, unknown> = {};
        const self = this as unknown as Record<string, (opts?: OutputOptions) => unknown>;

        for (const key of keys) {
            if (key === ("toJSON" as OutputKey) || key === ("toCustomOutput" as OutputKey)) {
                continue;
            }

            const internalKey = `${key}Internal`;
            const method = self[internalKey] || self[key];

            if (typeof method === "function") {
                let val: unknown;
                if (key === "toSlice") {
                    continue;
                } else {
                    val = method.call(this, options);
                }
                res[key] = typeof val === "bigint" ? val.toString() : val;
            }
        }

        res.signature = this.#signature;
        res.contextLabel = this.#config.contextLabel;

        return JSON.stringify(res, (_key, value) => typeof value === "bigint" ? value.toString() : value);
    }

    /**
     * Extends the output capabilities using a custom processor.
     *
     * @param processor - A custom function to transform the calculation result.
     * @param options - Custom processor options.
     * @returns The processed output.
     *
     * @example Financial: Generating a Binary Encoded Payload (Protobuffer)
     * ```ts
     * import { protobufProcessor } from "@st-all-one/calc-auy/protobuffer";
     *
     * const Treasury = CalcAUY.create({ contextLabel: "treasury", salt: "vault-key" });
     *
     * const result = await Treasury.from(150_000).add("0.5%").commit();
     *
     * // Pass a custom processor to generate optimized binary data
     * const binary = result.toCustomOutput(protobufProcessor);
     *
     * console.log(binary);
     * // <Buffer 0a 77 0a 09 6f 70 65 72 61 74 69 6f 6e 12 27 0a 09 74 69 6d 65 73 74 61 6d 70 12 1a 0a 18 32 30 32 36 2d 30 35 2d 30 33 54 31 33 3a 34 33 3a 32 37 2e ... 173 more bytes>
     * ```
     */
    public toCustomOutput<Toutput, Toptions extends OutputOptions = OutputOptions>(
        processor: CalcAUYCustomOutput<Toutput, Toptions>,
        options: Toptions = {} as Toptions,
    ): Toutput {
        using _span = startSpan("toCustomOutput", logger, options);

        if (!this.#cachedMethods) {
            this.#cachedMethods = Object.freeze({
                toStringNumber: this.toStringNumber.bind(this),
                toFloatNumber: this.toFloatNumber.bind(this),
                toScaledBigInt: this.toScaledBigInt.bind(this),
                toRawInternalNumber: this.toRawInternalNumber.bind(this),
                toLiveTrace: this.toLiveTrace.bind(this),
                toMonetary: this.toMonetary.bind(this),
                toLaTeX: this.toLaTeX.bind(this),
                toUnicode: this.toUnicode.bind(this),
                toMermaidGraph: this.toMermaidGraph.bind(this),
                toVerbalA11y: this.toVerbalA11y.bind(this),
                toSlice: this.toSlice.bind(this),
                toSliceByRatio: this.toSliceByRatio.bind(this),
                toAuditTrace: this.toAuditTrace.bind(this),
                toJSON: this.toJSON.bind(this),
            });
        }

        const context: CalcAUYCustomOutputContext<Toptions> = {
            result: this.#result,
            ast: this.#ast,
            roundStrategy: this.#roundStrategy,
            audit: {
                latex: this.toLaTeXInternal(options),
                unicode: this.toUnicodeInternal(options),
                verbal: this.toVerbalA11yInternal(options),
            },
            options,
            methods: this.#cachedMethods,
        };
        return processor.call(this, context);
    }
}
